select * FROM tbdepartamento;

INSERT INTO TBDEPARTAMENTO (SIGLA_DEP, NOME_DEP)
VALUES ('VD', 'Vendas');

INSERT INTO TBDEPARTAMENTO (SIGLA_DEP, NOME_DEP)
VALUES ('CP', 'Compras');

INSERT INTO TBDEPARTAMENTO (SIGLA_DEP, NOME_DEP)
VALUES ('RH', 'Recursos Humanos');